-- MySQL Script generated by MySQL Workbench
-- Fri Sep 24 12:45:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Faciales_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Faciales_DB` ;

-- -----------------------------------------------------
-- Schema Faciales_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Faciales_DB` DEFAULT CHARACTER SET utf8 ;
USE `Faciales_DB` ;

-- -----------------------------------------------------
-- Table `Faciales_DB`.`Cabinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Cabinas` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Cabinas` (
  `idCabinas` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Responsable` VARCHAR(45) NOT NULL,
  `Servicios_idServicios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCabinas`, `Servicios_idServicios`),
  CONSTRAINT `fk_Cabinas_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `Faciales_DB`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cabinas_Servicios1_idx` ON `Faciales_DB`.`Cabinas` (`Servicios_idServicios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Faciales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Faciales` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Faciales` (
  `idFaciales` VARCHAR(45) NOT NULL,
  `Servicios_idServicios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFaciales`, `Servicios_idServicios`),
  CONSTRAINT `fk_Faciales_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `Faciales_DB`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Faciales_Servicios1_idx` ON `Faciales_DB`.`Faciales` (`Servicios_idServicios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Marca` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Marca` (
  `Marca_id` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Teléfono` BIGINT(10) NOT NULL,
  PRIMARY KEY (`Marca_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Productos` (
  `idProductos` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Servicios` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Servicios` (
  `idServicios` VARCHAR(45) NOT NULL,
  `Categoría` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Duración` TIME NOT NULL,
  PRIMARY KEY (`idServicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Servicios_has_Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Servicios_has_Sucursal` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Servicios_has_Sucursal` (
  `Servicios_idServicios` VARCHAR(45) NOT NULL,
  `Sucursal_idSucursal` VARCHAR(45) NOT NULL,
  `Sucursal_Marca_Marca_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Servicios_idServicios`, `Sucursal_idSucursal`, `Sucursal_Marca_Marca_id`),
  CONSTRAINT `fk_Servicios_has_Sucursal_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `Faciales_DB`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicios_has_Sucursal_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal` , `Sucursal_Marca_Marca_id`)
    REFERENCES `Faciales_DB`.`Sucursal` (`idSucursal` , `Marca_Marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Servicios_has_Sucursal_Sucursal1_idx` ON `Faciales_DB`.`Servicios_has_Sucursal` (`Sucursal_idSucursal` ASC, `Sucursal_Marca_Marca_id` ASC) VISIBLE;

CREATE INDEX `fk_Servicios_has_Sucursal_Servicios1_idx` ON `Faciales_DB`.`Servicios_has_Sucursal` (`Servicios_idServicios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Sucursal` (
  `idSucursal` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Teléfono` BIGINT(10) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Marca_Marca_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSucursal`, `Marca_Marca_id`),
  CONSTRAINT `fk_Sucursal_Marca1`
    FOREIGN KEY (`Marca_Marca_id`)
    REFERENCES `Faciales_DB`.`Marca` (`Marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Sucursal_Marca1_idx` ON `Faciales_DB`.`Sucursal` (`Marca_Marca_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Sucursal_has_Cabinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Sucursal_has_Cabinas` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Sucursal_has_Cabinas` (
  `Sucursal_idSucursal` VARCHAR(45) NOT NULL,
  `Sucursal_Marca_Marca_id` VARCHAR(45) NOT NULL,
  `Cabinas_idCabinas` VARCHAR(45) NOT NULL,
  `Cabinas_Servicios_idServicios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sucursal_idSucursal`, `Sucursal_Marca_Marca_id`, `Cabinas_idCabinas`, `Cabinas_Servicios_idServicios`),
  CONSTRAINT `fk_Sucursal_has_Cabinas_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal` , `Sucursal_Marca_Marca_id`)
    REFERENCES `Faciales_DB`.`Sucursal` (`idSucursal` , `Marca_Marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_has_Cabinas_Cabinas1`
    FOREIGN KEY (`Cabinas_idCabinas` , `Cabinas_Servicios_idServicios`)
    REFERENCES `Faciales_DB`.`Cabinas` (`idCabinas` , `Servicios_idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Sucursal_has_Cabinas_Cabinas1_idx` ON `Faciales_DB`.`Sucursal_has_Cabinas` (`Cabinas_idCabinas` ASC, `Cabinas_Servicios_idServicios` ASC) VISIBLE;

CREATE INDEX `fk_Sucursal_has_Cabinas_Sucursal1_idx` ON `Faciales_DB`.`Sucursal_has_Cabinas` (`Sucursal_idSucursal` ASC, `Sucursal_Marca_Marca_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Tecnología`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Tecnología` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Tecnología` (
  `idTeconología` VARCHAR(45) NOT NULL,
  `Servicios_idServicios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTeconología`, `Servicios_idServicios`),
  CONSTRAINT `fk_Tecnología_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `Faciales_DB`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tecnología_Servicios1_idx` ON `Faciales_DB`.`Tecnología` (`Servicios_idServicios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Faciales_DB`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faciales_DB`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Faciales_DB`.`Usuarios` (
  `idUsuarios` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Puesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS Web;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Web' IDENTIFIED BY 'WebMaster2949';

GRANT ALL ON `Faciales_DB`.* TO 'Web';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Faciales_DB`.* TO 'Web';
GRANT SELECT, INSERT, TRIGGER ON TABLE `Faciales_DB`.* TO 'Web';
GRANT EXECUTE ON ROUTINE `Faciales_DB`.* TO 'Web';
SET SQL_MODE = '';
DROP USER IF EXISTS Facialsita;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Facialsita' IDENTIFIED BY 'facialista1234';

GRANT SELECT ON TABLE `Faciales_DB`.* TO 'Facialsita';
SET SQL_MODE = '';
DROP USER IF EXISTS Admin;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Admin' IDENTIFIED BY 'admin1234';

GRANT SELECT, INSERT, TRIGGER ON TABLE `Faciales_DB`.* TO 'Admin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Faciales_DB`.* TO 'Admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
